services:
  bot:
    build: .
    container_name: quest_rpg_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - YANDEX_CLOUD_FOLDER=${YANDEX_CLOUD_FOLDER}  # ← ДОБАВЬ
      - YANDEX_CLOUD_API_KEY=${YANDEX_CLOUD_API_KEY}  # ← ДОБАВЬ
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
