version: '3.8'

services:
  bot:
    build: .
    container_name: quest_rpg_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_KEY: ${API_KEY}
      DATABASE_TYPE: postgresql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: quest_bot
      DB_USER: quest_bot_user
      DB_PASSWORD: ${DB_PASSWORD}
      YANDEX_CLOUD_FOLDER: ${YANDEX_CLOUD_FOLDER}
      YANDEX_CLOUD_API_KEY: ${YANDEX_CLOUD_API_KEY}
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
